// Top programming concepts
const contentsList = [
  { title: "Home", categories: "Global", link: "Global/Home" },
  { title: "For", categories: "Loop", link: "Loop/For" },
  { title: "While", categories: "Loop", link: "Loop/While" },
  { title: "Do While", categories: "Loop", link: "Loop/DoWhile" },
  { title: "If", categories: "Conditional", link: "Conditional/If" },
  { title: "Else", categories: "Conditional", link: "Conditional/Else" },
  { title: "Else If", categories: "Conditional", link: "Conditional/ElseIf" },
  { title: "Switch", categories: "Conditional", link: "Conditional/Switch" },
  { title: "Function", categories: "Concept", link: "Concept/Function" },
  { title: "Arrow Function", categories: "Concept", link: "Concept/ArrowFunction" },
  { title: "Recursion", categories: "Concept", link: "Concept/Recursion" },
  { title: "Array", categories: "Data Structure", link: "DataStructure/Array" },
  { title: "Object", categories: "Data Structure", link: "DataStructure/Object" },
  { title: "Linked List", categories: "Data Structure", link: "DataStructure/LinkedList" },
  { title: "Stack", categories: "Data Structure", link: "DataStructure/Stack" },
  { title: "Queue", categories: "Data Structure", link: "DataStructure/Queue" },
  { title: "Hash Table", categories: "Data Structure", link: "DataStructure/HashTable" },
  { title: "Set", categories: "Data Structure", link: "DataStructure/Set" },
  { title: "Map", categories: "Data Structure", link: "DataStructure/Map" },
  { title: "Inheritance", categories: "OOP", link: "OOP/Inheritance" },
  { title: "Encapsulation", categories: "OOP", link: "OOP/Encapsulation" },
  { title: "Polymorphism", categories: "OOP", link: "OOP/Polymorphism" },
  { title: "Abstraction", categories: "OOP", link: "OOP/Abstraction" },
  { title: "Classes", categories: "OOP", link: "OOP/Classes" },
  { title: "Objects", categories: "OOP", link: "OOP/Objects" },
  { title: "Asynchronous Programming", categories: "Concept", link: "Concept/AsyncProgramming" },
  { title: "Promises", categories: "Concept", link: "Concept/Promises" },
  { title: "Async/Await", categories: "Concept", link: "Concept/AsyncAwait" },
  { title: "Error Handling", categories: "Concept", link: "Concept/ErrorHandling" },
  { title: "Module", categories: "Concept", link: "Concept/Module" },
  { title: "Closure", categories: "Concept", link: "Concept/Closure" },
  { title: "Scope", categories: "Concept", link: "Concept/Scope" },
  { title: "Event Loop", categories: "Concept", link: "Concept/EventLoop" },
  { title: "Regular Expressions", categories: "Concept", link: "Concept/Regex" },
  { title: "API", categories: "Concept", link: "Concept/API" },
  { title: "JSON", categories: "Data Format", link: "DataFormat/JSON" },
  { title: "XML", categories: "Data Format", link: "DataFormat/XML" },
  { title: "Database", categories: "Concept", link: "Concept/Database" },
  { title: "SQL", categories: "Database", link: "Database/SQL" },
  { title: "NoSQL", categories: "Database", link: "Database/NoSQL" },
  { title: "GraphQL", categories: "API", link: "API/GraphQL" },
  { title: "REST", categories: "API", link: "API/REST" },
  { title: "Data Structures and Algorithms", categories: "Concept", link: "Concept/DataStructuresAlgorithms" },
  { title: "Design Patterns", categories: "Concept", link: "Concept/DesignPatterns" },
  { title: "Version Control", categories: "Tool", link: "Tool/VersionControl" },
  { title: "Git", categories: "Tool", link: "Tool/Git" },
  { title: "Docker", categories: "Tool", link: "Tool/Docker" },
  { title: "Deployment", categories: "Concept", link: "Concept/Deployment" },
  { title: "Unit Testing", categories: "Testing", link: "Testing/UnitTesting" },
  { title: "Integration Testing", categories: "Testing", link: "Testing/IntegrationTesting" },
  { title: "End-to-End Testing", categories: "Testing", link: "Testing/E2ETesting" },
  { title: "Continuous Integration", categories: "DevOps", link: "DevOps/ContinuousIntegration" },
  { title: "Continuous Deployment", categories: "DevOps", link: "DevOps/ContinuousDeployment" },
];

export default contentsList;
