// Top programming concepts
const contentsList = [
  { title: "For", categories: "Loop", link: "Content/Loop/For" },
  { title: "While", categories: "Loop", link: "Content/Loop/While" },
  { title: "Do While", categories: "Loop", link: "Content/Loop/DoWhile" },
  { title: "If", categories: "Conditional", link: "Content/Conditional/If" },
  { title: "Else", categories: "Conditional", link: "Content/Conditional/Else" },
  { title: "Else If", categories: "Conditional", link: "Content/Conditional/ElseIf" },
  { title: "Switch", categories: "Conditional", link: "Content/Conditional/Switch" },
  { title: "Function", categories: "Concept", link: "Content/Concept/Function" },
  { title: "Arrow Function", categories: "Concept", link: "Content/Concept/ArrowFunction" },
  { title: "Recursion", categories: "Concept", link: "Content/Concept/Recursion" },
  { title: "Array", categories: "Data Structure", link: "Content/DataStructure/Array" },
  { title: "Object", categories: "Data Structure", link: "Content/DataStructure/Object" },
  { title: "Linked List", categories: "Data Structure", link: "Content/DataStructure/LinkedList" },
  { title: "Stack", categories: "Data Structure", link: "Content/DataStructure/Stack" },
  { title: "Queue", categories: "Data Structure", link: "Content/DataStructure/Queue" },
  { title: "Hash Table", categories: "Data Structure", link: "Content/DataStructure/HashTable" },
  { title: "Set", categories: "Data Structure", link: "Content/DataStructure/Set" },
  { title: "Map", categories: "Data Structure", link: "Content/DataStructure/Map" },
  { title: "Inheritance", categories: "OOP", link: "Content/OOP/Inheritance" },
  { title: "Encapsulation", categories: "OOP", link: "Content/OOP/Encapsulation" },
  { title: "Polymorphism", categories: "OOP", link: "Content/OOP/Polymorphism" },
  { title: "Abstraction", categories: "OOP", link: "Content/OOP/Abstraction" },
  { title: "Classes", categories: "OOP", link: "Content/OOP/Classes" },
  { title: "Objects", categories: "OOP", link: "Content/OOP/Objects" },
  { title: "Asynchronous Programming", categories: "Concept", link: "Content/Concept/AsyncProgramming" },
  { title: "Promises", categories: "Concept", link: "Content/Concept/Promises" },
  { title: "Async/Await", categories: "Concept", link: "Content/Concept/AsyncAwait" },
  { title: "Error Handling", categories: "Concept", link: "Content/Concept/ErrorHandling" },
  { title: "Module", categories: "Concept", link: "Content/Concept/Module" },
  { title: "Closure", categories: "Concept", link: "Content/Concept/Closure" },
  { title: "Scope", categories: "Concept", link: "Content/Concept/Scope" },
  { title: "Event Loop", categories: "Concept", link: "Content/Concept/EventLoop" },
  { title: "Regular Expressions", categories: "Concept", link: "Content/Concept/Regex" },
  { title: "API", categories: "Concept", link: "Content/Concept/API" },
  { title: "JSON", categories: "Data Format", link: "Content/DataFormat/JSON" },
  { title: "XML", categories: "Data Format", link: "Content/DataFormat/XML" },
  { title: "Database", categories: "Concept", link: "Content/Concept/Database" },
  { title: "SQL", categories: "Database", link: "Content/Database/SQL" },
  { title: "NoSQL", categories: "Database", link: "Content/Database/NoSQL" },
  { title: "GraphQL", categories: "API", link: "Content/API/GraphQL" },
  { title: "REST", categories: "API", link: "Content/API/REST" },
  { title: "Data Structures and Algorithms", categories: "Concept", link: "Content/Concept/DataStructuresAlgorithms" },
  { title: "Design Patterns", categories: "Concept", link: "Content/Concept/DesignPatterns" },
  { title: "Version Control", categories: "Tool", link: "Content/Tool/VersionControl" },
  { title: "Git", categories: "Tool", link: "Content/Tool/Git" },
  { title: "Docker", categories: "Tool", link: "Content/Tool/Docker" },
  { title: "Deployment", categories: "Concept", link: "Content/Concept/Deployment" },
  { title: "Unit Testing", categories: "Testing", link: "Content/Testing/UnitTesting" },
  { title: "Integration Testing", categories: "Testing", link: "Content/Testing/IntegrationTesting" },
  { title: "End-to-End Testing", categories: "Testing", link: "Content/Testing/E2ETesting" },
  { title: "Continuous Integration", categories: "DevOps", link: "Content/DevOps/ContinuousIntegration" },
  { title: "Continuous Deployment", categories: "DevOps", link: "Content/DevOps/ContinuousDeployment" },
];

export default contentsList;
